<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<LangVersion>latest</LangVersion>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<NoWarn>xUnit1051</NoWarn>
		<UserSecretsId>cisco-iq-api-tests</UserSecretsId>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="AwesomeAssertions.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Neovolve.Logging.Xunit.v3" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cisco.Iq.Api\Cisco.Iq.Api.csproj" />
		<None Update="Fixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
		<None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
